# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeYinBox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LeYinBox
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'LeYinBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LeYinBox-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LeYinBox-tvOS

  target 'LeYinBox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
